SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes' AND TABLE_NAME='datospersonas' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `datospersonas` FROM `pacientes`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes'   AND TABLE_NAME='datospersonas'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes'   AND TABLE_NAME='datospersonas'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes`.`datospersonas`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes' AND TABLE_NAME='datospersonas';
SHOW CREATE TABLE `pacientes`.`departamentos`;
USE `pacientes 3`;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`departamentos`;
SELECT * FROM `pacientes`.`departamentos` LIMIT 1000;
USE `pacientes 3`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes 3' AND TABLE_NAME='departamentos' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `departamentos` FROM `pacientes 3`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes 3'   AND TABLE_NAME='departamentos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes 3'   AND TABLE_NAME='departamentos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes 3`.`departamentos`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes 3' AND TABLE_NAME='departamentos';
SELECT * FROM `pacientes 3`.`departamentos` LIMIT 1000;
INSERT INTO `pacientes 3`.`departamentos` (`nombredepartamentos`) VALUES ('ANTIOQUIA');
SELECT LAST_INSERT_ID();
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=1;
UPDATE `pacientes 3`.`departamentos` SET `nombredepartamentos`='Antioquia' WHERE  `id_departamento`=1;
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=1;
INSERT INTO `pacientes 3`.`departamentos` (`nombredepartamentos`) VALUES ('Caldas');
SELECT LAST_INSERT_ID();
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=2;
INSERT INTO `pacientes 3`.`departamentos` (`nombredepartamentos`) VALUES ('Cundinamarca');
SELECT LAST_INSERT_ID();
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=3;
INSERT INTO `pacientes 3`.`departamentos` (`nombredepartamentos`) VALUES ('Guajira');
SELECT LAST_INSERT_ID();
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=4;
INSERT INTO `pacientes 3`.`departamentos` (`nombredepartamentos`) VALUES ('Tolima');
SELECT LAST_INSERT_ID();
SELECT `id_departamento`, `nombredepartamentos` FROM `pacientes 3`.`departamentos` WHERE  `id_departamento`=5;
USE `pacientes`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes' AND TABLE_NAME='municipios' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `municipios` FROM `pacientes`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes'   AND TABLE_NAME='municipios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes'   AND TABLE_NAME='municipios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes`.`municipios`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes' AND TABLE_NAME='municipios';
SELECT * FROM `pacientes`.`municipios` LIMIT 1000;
USE `pacientes 3`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes 3' AND TABLE_NAME='municipios' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `municipios` FROM `pacientes 3`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes 3'   AND TABLE_NAME='municipios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes 3'   AND TABLE_NAME='municipios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes 3`.`municipios`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes 3' AND TABLE_NAME='municipios';
SELECT * FROM `pacientes 3`.`municipios` LIMIT 1000;
SELECT * FROM `pacientes 3`.`municipios` ORDER BY `id_municipio` ASC LIMIT 1000;
SELECT * FROM `pacientes 3`.`municipios` ORDER BY `id_municipio` DESC LIMIT 1000;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('1', 'Bello');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=1;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('3', 'Cota');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=2;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('3', 'Chia');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=3;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('5', 'Anzoategui');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=4;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('5', 'Ibague');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=5;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`) VALUES ('4');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=6;
UPDATE `pacientes 3`.`municipios` SET `nombremunicipio`='Maicao' WHERE  `id_municipio`=6;
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=6;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`) VALUES ('2');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=7;
UPDATE `pacientes 3`.`municipios` SET `nombremunicipio`='Manizales' WHERE  `id_municipio`=7;
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=7;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('1', 'Medellin');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=8;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('4', 'Rioacha');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=9;
SELECT `id_departamento`, LEFT(`nombredepartamentos`, 256) FROM `pacientes 3`.`departamentos` GROUP BY `id_departamento`, `nombredepartamentos` ORDER BY `nombredepartamentos` LIMIT 10000;
INSERT INTO `pacientes 3`.`municipios` (`id_departamento`, `nombremunicipio`) VALUES ('2', 'Palestina');
SELECT LAST_INSERT_ID();
SELECT `id_municipio`, `id_departamento`, `nombremunicipio` FROM `pacientes 3`.`municipios` WHERE  `id_municipio`=10;
USE `pacientes`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes' AND TABLE_NAME='usuarios' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `usuarios` FROM `pacientes`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes'   AND TABLE_NAME='usuarios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes'   AND TABLE_NAME='usuarios'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes' AND TABLE_NAME='usuarios';
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes 3' AND TABLE_NAME='datospersonas' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `datospersonas` FROM `pacientes 3`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes 3'   AND TABLE_NAME='datospersonas'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes 3'   AND TABLE_NAME='datospersonas'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes 3`.`datospersonas`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes 3' AND TABLE_NAME='datospersonas';
SELECT * FROM `pacientes 3`.`datospersonas` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes 3' AND TABLE_NAME='documentos' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `documentos` FROM `pacientes 3`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes 3'   AND TABLE_NAME='documentos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes 3'   AND TABLE_NAME='documentos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes 3`.`documentos`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes 3' AND TABLE_NAME='documentos';
SELECT * FROM `pacientes 3`.`documentos` LIMIT 1000;
INSERT INTO `pacientes 3`.`documentos` (`tipodocumento`) VALUES ('TI');
SELECT LAST_INSERT_ID();
SELECT `id_documento`, `tipodocumento` FROM `pacientes 3`.`documentos` WHERE  `id_documento`=1;
INSERT INTO `pacientes 3`.`documentos` (`tipodocumento`) VALUES ('CC');
SELECT LAST_INSERT_ID();
SELECT `id_documento`, `tipodocumento` FROM `pacientes 3`.`documentos` WHERE  `id_documento`=2;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
SHOW CREATE TABLE `pacientes`.`documentos`;
SELECT * FROM `pacientes`.`documentos` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
SHOW CREATE TABLE `pacientes 3`.`documentos`;
SELECT * FROM `pacientes 3`.`documentos` LIMIT 1000;
INSERT INTO `pacientes 3`.`documentos` (`tipodocumento`) VALUES ('RC');
SELECT LAST_INSERT_ID();
SELECT `id_documento`, `tipodocumento` FROM `pacientes 3`.`documentos` WHERE  `id_documento`=3;
SHOW CREATE TABLE `pacientes 3`.`departamentos`;
SELECT * FROM `pacientes 3`.`departamentos` LIMIT 1000;
SHOW CREATE TABLE `pacientes 3`.`datospersonas`;
SELECT * FROM `pacientes 3`.`datospersonas` LIMIT 1000;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes 3' AND TABLE_NAME='generos' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `generos` FROM `pacientes 3`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes 3'   AND TABLE_NAME='generos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes 3'   AND TABLE_NAME='generos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes 3`.`generos`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes 3' AND TABLE_NAME='generos';
SELECT * FROM `pacientes 3`.`generos` LIMIT 1000;
USE `pacientes`;
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='pacientes' AND TABLE_NAME='generos' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `generos` FROM `pacientes`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='pacientes'   AND TABLE_NAME='generos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='pacientes'   AND TABLE_NAME='generos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `pacientes`.`generos`;
SELECT * FROM `information_schema`.`CHECK_CONSTRAINTS` WHERE CONSTRAINT_SCHEMA='pacientes' AND TABLE_NAME='generos';
SELECT * FROM `pacientes`.`generos` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`generos`;
SELECT * FROM `pacientes 3`.`generos` LIMIT 1000;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
SHOW CREATE TABLE `pacientes`.`generos`;
SELECT * FROM `pacientes`.`generos` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`generos`;
SELECT * FROM `pacientes 3`.`generos` LIMIT 1000;
INSERT INTO `pacientes 3`.`generos` (`genero`) VALUES ('F');
SELECT LAST_INSERT_ID();
SELECT `id_genero`, `genero` FROM `pacientes 3`.`generos` WHERE  `id_genero`=1;
INSERT INTO `pacientes 3`.`generos` (`genero`) VALUES ('M');
SELECT LAST_INSERT_ID();
SELECT `id_genero`, `genero` FROM `pacientes 3`.`generos` WHERE  `id_genero`=2;
SHOW CREATE TABLE `pacientes 3`.`datospersonas`;
SELECT * FROM `pacientes 3`.`datospersonas` LIMIT 1000;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`datospersonas`;
SELECT * FROM `pacientes`.`datospersonas` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`datospersonas`;
SELECT * FROM `pacientes 3`.`datospersonas` LIMIT 1000;
INSERT INTO `pacientes 3`.`datospersonas` (`nombre1`, `nombre2`, `apellido1`) VALUES ('Victor', 'Arley', 'Santamaria');
SELECT LAST_INSERT_ID();
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=1 AND `numerodocumento`=0;
UPDATE `pacientes 3`.`datospersonas` SET `apellido2`='Castellanos' WHERE  `id_datos`=1 AND `numerodocumento`=0;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=1 AND `numerodocumento`=0;
UPDATE `pacientes 3`.`datospersonas` SET `numerodocumento`='1006117214' WHERE  `id_datos`=1 AND `numerodocumento`=0;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=1 AND `numerodocumento`=1006117214;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='2', `genero`='2', `id_municipio`='4', `usuario`='1' WHERE  `id_datos`=1 AND `numerodocumento`=1006117214;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=1 AND `numerodocumento`=1006117214;
INSERT INTO `pacientes 3`.`datospersonas` (`nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`) VALUES ('Maria', 'Helena', 'Santamaria', 'Castellanos', '38245213');
SELECT LAST_INSERT_ID();
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=2 AND `numerodocumento`=38245213;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='1', `id_municipio`='10' WHERE  `id_datos`=2 AND `numerodocumento`=38245213;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=2 AND `numerodocumento`=38245213;
UPDATE `pacientes 3`.`datospersonas` SET `usuario`='2' WHERE  `id_datos`=2 AND `numerodocumento`=38245213;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=2 AND `numerodocumento`=38245213;
INSERT INTO `pacientes 3`.`datospersonas` (`nombre1`, `nombre2`, `apellido1`, `apellido2`) VALUES ('Faber', 'Job', 'Muñoz', 'Lombana');
SELECT LAST_INSERT_ID();
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=3 AND `numerodocumento`=0;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `numerodocumento`='93876654', `tipodocumento`='2', `genero`='1', `id_municipio`='6', `usuario`='3' WHERE  `id_datos`=3 AND `numerodocumento`=0;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=3 AND `numerodocumento`=93876654;
INSERT INTO `pacientes 3`.`datospersonas` (`nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`) VALUES ('Fabian ', 'Andres', 'Lombana', 'Sanchez', '2345676523');
SELECT LAST_INSERT_ID();
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7', `usuario`='4' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
/* #1634496361: Access violation at address 0000001000000000 in module 'heidisql.exe'. Execution of address 0000001000000000 Message CharCode:13 Msg:256 */
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7', `usuario`='4' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7', `usuario`='' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='3', `genero`='2', `id_municipio`='7', `usuario`='' WHERE  `id_datos`=4 AND `numerodocumento`=2345676523;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
INSERT INTO `pacientes 3`.`usuarios` (`usuario`, `clave`) VALUES ('vs', '2714');
SELECT `usuario`, `clave`, `id_datos` FROM `pacientes 3`.`usuarios` WHERE  `usuario`='vs';
UPDATE `pacientes 3`.`usuarios` SET `clave`='7214' WHERE  `usuario`='vs';
SELECT `usuario`, `clave`, `id_datos` FROM `pacientes 3`.`usuarios` WHERE  `usuario`='vs';
UPDATE `pacientes 3`.`usuarios` SET `usuario`='1006117214' WHERE  `usuario`='vs';
SELECT `usuario`, `clave`, `id_datos` FROM `pacientes 3`.`usuarios` WHERE  `usuario`='1006117214';
SELECT `id_datos`, LEFT(`nombre1`, 256) FROM `pacientes 3`.`datospersonas` GROUP BY `id_datos`, `nombre1` ORDER BY `nombre1` LIMIT 10000;
UPDATE `pacientes 3`.`usuarios` SET `id_datos`='1' WHERE  `usuario`='1006117214';
SELECT `usuario`, `clave`, `id_datos` FROM `pacientes 3`.`usuarios` WHERE  `usuario`='1006117214';
USE `pacientes`;
SHOW CREATE TABLE `pacientes`.`usuarios`;
SELECT * FROM `pacientes`.`usuarios` LIMIT 1000;
USE `pacientes 3`;
SHOW CREATE TABLE `pacientes 3`.`datospersonas`;
SELECT * FROM `pacientes 3`.`datospersonas` LIMIT 1000;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='1', `genero`='1', `id_municipio`='1' WHERE  `id_datos`=4 AND `numerodocumento`=2147483647;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=4 AND `numerodocumento`=2147483647;
INSERT INTO `pacientes 3`.`datospersonas` (`nombre1`, `nombre2`) VALUES ('Michel', 'Dayana');
SELECT LAST_INSERT_ID();
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=5 AND `numerodocumento`=0;
UPDATE `pacientes 3`.`datospersonas` SET `apellido1`='Santamaria', `apellido2`='Castellanos' WHERE  `id_datos`=5 AND `numerodocumento`=0;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=5 AND `numerodocumento`=0;
UPDATE `pacientes 3`.`datospersonas` SET `numerodocumento`='1006117216' WHERE  `id_datos`=5 AND `numerodocumento`=0;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=5 AND `numerodocumento`=1006117216;
SELECT `id_documento`, LEFT(`tipodocumento`, 256) FROM `pacientes 3`.`documentos` GROUP BY `id_documento`, `tipodocumento` ORDER BY `tipodocumento` LIMIT 10000;
SELECT `id_genero`, LEFT(`genero`, 256) FROM `pacientes 3`.`generos` GROUP BY `id_genero`, `genero` ORDER BY `genero` LIMIT 10000;
SELECT `id_municipio`, LEFT(`nombremunicipio`, 256) FROM `pacientes 3`.`municipios` GROUP BY `id_municipio`, `nombremunicipio` ORDER BY `nombremunicipio` LIMIT 10000;
UPDATE `pacientes 3`.`datospersonas` SET `tipodocumento`='2', `genero`='1', `id_municipio`='1' WHERE  `id_datos`=5 AND `numerodocumento`=1006117216;
SELECT `id_datos`, `nombre1`, `nombre2`, `apellido1`, `apellido2`, `numerodocumento`, `tipodocumento`, `genero`, `id_municipio`, `usuario` FROM `pacientes 3`.`datospersonas` WHERE  `id_datos`=5 AND `numerodocumento`=1006117216;
SHOW CREATE TABLE `pacientes 3`.`usuarios`;
SELECT * FROM `pacientes 3`.`usuarios` LIMIT 1000;
USE `pacientes`;
SHOW /*!50002 GLOBAL */ STATUS LIKE 'Com\_%';
DROP DATABASE `pacientes`;
SHOW DATABASES;
USE `pacientes 3`;
SHOW VARIABLES;
SHOW CREATE DATABASE `pacientes 3`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='pacientes 3';
SHOW TABLE STATUS FROM `pacientes 3`;
SHOW FUNCTION STATUS WHERE `Db`='pacientes 3';
SHOW PROCEDURE STATUS WHERE `Db`='pacientes 3';
SHOW TRIGGERS FROM `pacientes 3`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='pacientes 3';
SHOW DATABASES;
CREATE DATABASE `pacientes ` /*!40100 COLLATE 'latin1_swedish_ci' */;
/* Error de SQL (1102): Incorrect database name 'pacientes ' */